apiVersion: v1
kind: Service
metadata:
  name: antigravity-load-test-service
spec:
  type: LoadBalancer # Or NodePort for Minikube
  selector:
    app: antigravity-load-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
